# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=150)),
                ('market_name', models.CharField(blank=True, max_length=40, null=True)),
                ('asset_class', models.CharField(blank=True, max_length=40, null=True)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yahoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
