# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='asset_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='market_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
