# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0002_auto_20160422_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baidu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biogen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Celgene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='illumina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priceline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regeneron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tesla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Texas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vodafone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opent', models.FloatField(blank=True, default=0.0, null=True)),
                ('high', models.FloatField(blank=True, default=0.0, null=True)),
                ('low', models.FloatField(blank=True, default=0.0, null=True)),
                ('close', models.FloatField(blank=True, default=0.0, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('adjclose', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
