# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=25, null=True, verbose_name='Symbol')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('market_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Market Name')),
                ('asset_class', models.CharField(blank=True, max_length=40, null=True, verbose_name='Asset class')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Weight')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('companies', models.ManyToManyField(to='portfolio.Company')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'verbose_name': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic', verbose_name='Profile Pic')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'verbose_name': 'Profile',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
