# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='killu', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(default='yt', max_length=25, verbose_name='Symbol'),
            preserve_default=False,
        ),
    ]
